version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=test
      - DATABASE_PASSWORD=test
      - DATABASE_NAME=test
    
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test